=== dzmauchy/tybaco/ui/src/main/resources/l10n/l10n.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="localization">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="key" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="val" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="lang" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="value" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dzmauchy/tybaco/ui/src/main/resources/l10n/texts.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  #%L
  ui
  %%
  Copyright (C) 2023 Montoni
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  #L%
  -->

<localization xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="l10n.xsd">
  <key value="Project">
    <val lang="es">Proyecto</val>
  </key>
  <key value="Languages">
    <val lang="es">Idiomas</val>
  </key>
  <key value="Set to system default">
    <val lang="es">Usar un idioma por defecto</val>
  </key>
  <key value="New project">
    <val lang="es">Nuevo proyecto</val>
  </key>
  <key value="Save all projects">
    <val lang="es">Guardar todos los proyectos</val>
  </key>
  <key value="New block">
    <val lang="es">Nuevo bloco</val>
  </key>
  <key value="Right pane visibility">
    <val lang="es">Visibilidad de la pestaña derecha</val>
  </key>
  <key value="Add a dependency">
    <val lang="es">Añadir una dependencia</val>
  </key>
  <key value="Dependencies">
    <val lang="es">Dependencias</val>
  </key>
  <key value="Constants">
    <val lang="es">Constantes</val>
  </key>
</localization>
