=== dzmauchy/tybaco/library/src/main/resources/tybaco/library/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="library">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="constants" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="constant" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="icon" type="xs:string" use="required"/>
                  <xs:attribute name="factory" type="xs:string" use="required"/>
                  <xs:attribute name="description" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="icon" type="xs:string" use="required"/>
            <xs:attribute name="description" type="xs:string"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="blocks" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="block" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="param" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="icon" type="xs:string"/>
                        <xs:attribute name="description" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="icon" type="xs:string" use="required"/>
                  <xs:attribute name="factory" type="xs:string" use="required"/>
                  <xs:attribute name="method" type="xs:string" use="required"/>
                  <xs:attribute name="description" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="icon" type="xs:string" use="required"/>
            <xs:attribute name="description" type="xs:string"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="type" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="input" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="icon" type="xs:string"/>
                  <xs:attribute name="description" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="output" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="icon" type="xs:string"/>
                  <xs:attribute name="description" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="icon" type="xs:string" use="required"/>
            <xs:attribute name="description" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="icon" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dzmauchy/tybaco/runtime/src/main/resources/tybaco/library/library.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  #%L
  runtime
  %%
  Copyright (C) 2023 Montoni
  %%
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
  #L%
  -->

<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="library.xsd" name="Basic library" icon="eli-delicious">
  <constants name="Network constants" icon="mdi2n-network" description="Network-specific constants like URI, URL, NetworkInterface">
    <constant name="URI" icon="mdi2l-link" factory="java.net.URI"/>
    <constant name="URL" icon="mdi2l-link-box" factory="java.net.URL"/>
    <constant name="NetworkInterface" icon="mdi2n-network-outline" factory="java.net.NetworkInterface"/>
  </constants>
  <types>
    <type name="java.lang.String" icon="mdi2t-text-box" description="A text"/>
    <type name="int" icon="mdi2n-numeric" description="An integer number"/>
  </types>
</library>
